src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TodoRepository::class)]
class Todo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'todos')]
    private ?User $user = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $modified_at = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modified_at;
    }

    public function setModifiedAt(?\DateTimeInterface $modified_at): static
    {
        $this->modified_at = $modified_at;

        return $this;
    }
}

src/Form/TodoType.php
<?php

namespace App\Form;

use App\Entity\Todo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use function SebastianBergmann\Type\TestFixture\objectReturnType;
use function Webmozart\Assert\Tests\StaticAnalysis\object;

class TodoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('content')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Todo::class,
        ]);
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use App\Entity\Todo;
use App\Entity\User;
use App\Form\TodoType;
use App\Repository\TodoRepository;
use App\Security\UserAuthenticator;
use Doctrine\ORM\EntityManagerInterface;
use Monolog\DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;


#[Route('/todo')]
class TodoController extends AbstractController
{
    #[Route('/', name: 'app_todo_index', methods: ['GET'])]
    public function index(EntityManagerInterface $em,TodoRepository $todoRepository , Request $request, AuthenticationUtils $authenticationUtils): Response
    {
        $currentUserEmail ='';
        if ($this->getUser()) {
//             return $this->redirectToRoute('app_todo_index');
            $currentUserEmail = $authenticationUtils->getLastUsername();
            $currentUser = $em->getRepository(User::class)->findBy(['email' => $currentUserEmail]);

        }


        return $this->render('todo/index.html.twig', ['todos' => $todoRepository->findAll()]);
    }

    #[Route('/new', name: 'app_todo_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $em,AuthenticationUtils $authenticationUtils): Response
    {
        $todo = new Todo();
        $form = $this->createForm(TodoType::class, $todo);
        $form->handleRequest($request);

        $currentId = $this->getUser()->getId();

        if ($form->isSubmitted() && $form->isValid()) {
            $todo->setCreatedAt(date_create_immutable('now'));
            $todo->setUser($currentId);
            $em->persist($todo);
            $em->flush();
            return $this->redirectToRoute('app_todo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('todo/new.html.twig', [
            'todo' => $todo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_todo_show', methods: ['GET'])]
    public function show(Todo $todo): Response
    {
        return $this->render('todo/show.html.twig', [
            'todo' => $todo,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_todo_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Todo $todo, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TodoType::class, $todo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $todo->setModifiedAt(date_create_immutable('now'));
            $entityManager->flush();

            return $this->redirectToRoute('app_todo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('todo/edit.html.twig', [
            'todo' => $todo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_todo_delete', methods: ['POST'])]
    public function delete(Request $request, Todo $todo, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$todo->getId(), $request->request->get('_token'))) {
            $entityManager->remove($todo);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_todo_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/todo/_delete_form.html.twig
<form method="post" action="{{ path('app_todo_delete', {'id': todo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ todo.id) }}">
    <button class="btn">Delete</button>
</form>

templates/todo/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/todo/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Todo{% endblock %}

{% block body %}
    <h1>Edit Todo</h1>

    {{ include('todo/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_todo_index') }}">back to list</a>

    {{ include('todo/_delete_form.html.twig') }}
{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Todo index{% endblock %}

{% block body %}
    <h1>Todo index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Content</th>
                <th>Created_at</th>
                <th>Modified_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for todo in todos %}
            <tr>
                <td>{{ todo.name }}</td>
                <td>{{ todo.content }}</td>
                <td>{{ todo.createdAt ? todo.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ todo.modifiedAt ? todo.modifiedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_todo_show', {'id': todo.id}) }}">show</a>
                    <a href="{{ path('app_todo_edit', {'id': todo.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_todo_new') }}">Create new</a>
{% endblock %}

templates/todo/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Todo{% endblock %}

{% block body %}
    <h1>Create new Todo</h1>

    {{ include('todo/_form.html.twig') }}

    <a href="{{ path('app_todo_index') }}">back to list</a>
{% endblock %}

templates/todo/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Todo{% endblock %}

{% block body %}
    <h1>Todo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ todo.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ todo.name }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ todo.content }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ todo.createdAt ? todo.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Modified_at</th>
                <td>{{ todo.modifiedAt ? todo.modifiedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_todo_index') }}">back to list</a>

    <a href="{{ path('app_todo_edit', {'id': todo.id}) }}">edit</a>

    {{ include('todo/_delete_form.html.twig') }}
{% endblock %}